### PR TITLE
Update retraction speeds and lengths

### PR DESCRIPTION
**Pull request by newphreak**
I changed all default lengths and speeds to both be consistent and have a short default length. Yanking it 10mm back at 60mm/s is just asking for trouble. There's been many clogs because of these defaults. This is a safe startingpoint that might be a little annoying with ooze during next print, but users can tweak this WITHOUT a clogged hotend.

### CODE REVIEW

**Comment by bythorsthunder** [comment]
This is a very worthwhile change in my opinion. The very long and fast retractions have been a source of clogs for many new users.

**Comment by cbc02009** [comment]
Yeah, this is a great change. we should get it merged as soon as possible.

**Comment by newphreak** [comment]
Yes please. Yell if something more is needed on my part.

**Review by shiftingtech — APPROVED** [review]
This checks out.  I like having us consistent across all the stock configs, and I *think* these values should be a reasonable starting place for most toolheads

**Pull request merged**
