### PR TITLE
Add reference config file for BTT Octopus board

### PR DESCRIPTION
**Pull request by cbc02009**
This config file should be complete, but feel free to leave any comments. 

I don't have a wiring diagram to go with it unfortunately.

### CODE REVIEW

**Comment by shiftingtech** [comment]
Is there an advantage to this config over the one in #249 ?

**Comment by cbc02009** [comment]
> 
> 
> Is there an advantage to this config over the one in #249 ?

The other config has several issues (like a missing [probe] section) that haven't been updated/fixed. See the review I did here: https://github.com/VoronDesign/Voron-2/pull/249/files/95ca7be0b322f415134452068cd595147f343738

**Comment by Knechtie** [comment]
Maybe we should add [pin aliases](https://github.com/VoronDesign/VoronUsers/blob/master/firmware_configurations/klipper/revnull/btt_octopus_pins/btt_octopus_pin_aliases.cfg) at the top of the config and replace the existing pin definitions with those aliases. This makes it easier to read/change the config. ([Klipper config docs](https://www.klipper3d.org/Config_Reference.html#board_pins), [more information regarding aliases](https://github.com/Klipper3d/klipper/issues/3485))

Regarding wiring: I found something existing in the [Voron docs](https://docs.vorondesign.com/build/electrical/v2_octopus_wiring.html). We should change the config to match the existing wiring diagram.

**Comment by cbc02009** [comment]
needs updating since BTT added their wiring diagram to the docs. need to move the motors around.

**Comment by cbc02009** [comment]
Update finished. Should now match the wiring guide on the docs site.

**Comment by cbc02009** [comment]
need to fix probe pin for octopus pro. should be ~!PC5
need to reduce z height choices.

EDIT: Done

**Comment by cbc02009** [comment]
@shiftingtech Do you know who needs to approve this for it to get merged?

**Review by raymondh2 — APPROVED** [review]

**Review by KiloQubit — APPROVED** [review]

**Pull request merged**
