### PR TITLE
Z endstop fix

### PR DESCRIPTION
**Pull request by eddietheengineer**
Fix slight (potential) interference between Z endstop/nozzle probe and bed.

### CODE REVIEW

**Review by Spaghetti-Bolognese — CHANGES_REQUESTED** [review]
Hi, this is Spaghetti_bolognese V2.427#3228 from Discord. Thanks again for the quick work on this issue. I've noticed that this shorter endstop doesn't have the JST connector plug fitment detail on the bottom, which the current taller V2.4 version does have. I think it would be good to keep that to make it neater when installing the plug.
Capture

**Comment by Spaghetti-Bolognese** [comment]
I've gone ahead and altered the current tall endstop so as to keep the JST plug fitment detail. I removed 3mm from its height. Here is the STL and Fusion360 file
[Short Z Endstop.zip](https://github.com/VoronDesign/Voron-2/files/4872325/Short.Z.Endstop.zip)

**Comment by eddietheengineer** [comment]
@Conrad94 great catch, have you printed your modified part?

**Comment by Spaghetti-Bolognese** [comment]
@jdlongenecker I have indeed and assembled. Its working perfectly :)

**Review by FHeilmann — APPROVED** [review]

**Pull request merged**
