### PR TITLE
Voron 2.4r2 Update

### LINKED ISSUE #229: [V2.4] Manual Enhancement: Connecting DC-0 of power supplies  / reference to docs.vorondesign.com
Online Voron Design documentation recommends to connect DC 0 of the power supplies to ensure a correct voltage reference. (https://docs.vorondesign.com/build/electrical/#dc-power-supply-wiring)

This should be added to the manual, too. Perhaps on page 120 "Low Voltage Power". or at least on page 129 (pre-flight checklist)

Many people use the manual from GitHub for building  and don't know about the docs.vorondesign.com resource.

Maybe it is a good idea to put a reference to the online documentation into the introduction pages, too.

### LINKED ISSUE #237: [V2.4] SKR 1.4 AB motor pinout different in config vs guide
The motor connections in the guide for AB motors are opposite what they are in the config:

wiring guide (pg 2):
image

config:
```
[stepper_x]
##	Connected to X on mcu_xye (B Motor)
...
[stepper_y]
##	Connected to Y on mcu_xye (A Motor)
...
```

Someone pointed this out on discord so I figured I'd create an issue.

### LINKED ISSUE #255: AB Idler Belt Wear
I have a suggestion for improving the AB front idlers as I've had some damage to my belts due to how they are designed. Currently, the idlers are tightened using a screw at the front which are aligned to the centre of the idler, however as the belt idler is either at the top or bottom depending on which side it sits this creates a rotational force which mis-aligns the idler bearing giving it a slight angle. This angle causes the belt to rub at one end causing wear to the belt. I suggest moving the screw so that it is in line with the centre of the idler bearing so that there is no rotational force. For my printer, I plan to make a few spacer wedges that I can stick in the idler to stop this rotation, but just moving the tensioner screw in the design would fix this quite easily. Only downside is it would not look symmetrical from the front.

idler

### LINKED ISSUE #260: [V2.4] Manual Enhancement: Adding Comment on VHB, and some revamps.
Hello friendly Admin who reads this,

as i was in the last steps of building my V2 i found a page in the actual manual which i think could be added with an information that can be copy-pasted from a few pages before. Therefore i scrolled through the entire manual again to mark some spots that may be confusing.
- Page 23 shows the old motor mount, but i think you are aware of that.
- Page 34 shows the old printed part for the z endstop pin, maybe a comment about fitting should be added.
- On Page 78 lower left picture doesn´t belong there and can cause confusion. In addition the upper left pic on page 79 could be fitted to page 78 after deleting the wrong one. Then you would have a closed workstep.
- Maybe a hint on Page 99 that there are two different parts "belt_guard_**a**_x2.stl" and "belt_guard_**b**_x2.stl". They are only slightly different but if you know that they are, you can realize which to mount on each corner.
- Finally page 106, which shows mounting of the bottom panel. I assume there has to be VHB to fix the clips and latches to the panel? If so, just copy the comment on VHB from page 102. If not, a description on how to fix the hinges would be nice.

Nevertheless, thank you for all your time and effort to create and maintain such a detailed manual. 

greetings
khay

### LINKED ISSUE #267: Pages accidentally deleted from manual
As [pointed out](https://github.com/VoronDesign/Voron-2/pull/238#commitcomment-53036713) by @rdenouden, some important bits appear to have been accidentally removed from the manual.

### LINKED ISSUE #273: [V2.4] Manual enhancement fixes and comments.
Page 44-45 AB motor wire direction.
Page 48-49, 1 of the screws does NOT attached to the top piece, which is perfect, but the diagram does a poor job of showing this.
Page 50 the cable chain, could be rotated slightly, it looks a bit weird in the diagram.
Page 57, would be nice to flip the diagrams, since you are assembling it upside down.
page 60, m3x20 should be m3x25, could be just my omron sensor? But i doubt it.
page 60, wire should be in the wire guide photo shows it on top of the guide (rather than in it)
page 61, option button head screws if you have them, is confusing. (maybe smaller? or somehow define it in the language used BHCS M3x8)
page 66, would be nice to show the dragon option on this page.
Page 76, should be a 25mm screw not a 30mm screw.
Page 78, why show the shroud? its on the next page to install it. just confusing, showing it with a screw highlighted and no size. All the instructions for this are on the next page.
page 80, two fan just APPEARS! One decased and installed. No wire routing visible, nothing (maybe worth showing at least a little of this! (this is the first part i notice a step being skipped)
page 85, maybe say make 4 of these
page 93, have to use "hammer head" tnuts, rather than drop-ins, or m3x8 is too short, would need m3x10 (m3x12 is too long)
page 94, m3x12 can be subbed, maybe worth noting as a lot of kits wont have the 2 self tapers
Page 128-130, hint to use the "hammer head" Tnuts or spacing wont work, also maybe just show the little dog bone with 2 m3 nuts at this point, no reason to have it displayed like 100 pages back since it wont hold in place. screw sizes missing in a few places

Enhancement
	- Show all the printed parts for a section.
	- Maybe do all the heat sets in one step. Like done for the hotend, this makes it a little easier/one step.
	- screw size/pulley/shafts size 1:1 on side of page where used (a la lego technic manual)
	- accent vs non accent colour pieces
	- count of units to make, a la lego technic manual, when you need to make 2, or 4, and if one is mirror image or not.
	- maybe some sort of marker to indicate parts are "bootstrap/part of pif/essential set sold by a lot of ppl to get someone started"

### LINKED ISSUE #276: Assembly Manual 2021 05 20 page 20 missing part
On page 20, the Z drive assembly, the 60mmx5mm shaft (x4) is not mentioned. This is an error.
Cheers,
Bob

### LINKED ISSUE #277: Assembly Manual 2021 05 20 page 23 incorrect image
The printed z motor mounts do not correspond to those pictured in the manual. This is confusing, of course.

Cheers,
Bob

### LINKED ISSUE #298: [V2.4] Assembly Manual steps missing leading to Front Idler Assembly (page 39-40)
For someone who never saw a Voron, there might be steps missing between current page 39 and page 40. From talking about heat sets in the Front Idler Tensioners, the manual jumps into an almost assembled Front Idler Assembly without any view of the parts you are attaching the Front Idler Tensioners to. An exploded view of the assembly and their orientation before showing the two parts joined would be welcome.

Screenshot 2022-01-25 at 23 54 55

### PR DESCRIPTION
**Pull request by stvptrsn**
Draft change log:
- MGN12 X Axis setup from Trident (originally member contributed)
-- (note: as with Trident, the MGN12 setup drops compatibility with the PL series of inductive probes)
- Revised Z drive modules to fit guitar amplifier feet introduced with Trident.  Maintains compatibility with compressor feet.
-- Requires a modification to the bottom panel for upgrades from V2.4r1.  Cut template included in the tools folder.
- New rear skirt layout relocating the power inlet and keystone pieces.
- Most unsupported countersunk bolt holes changed to using the cross-bridge method instead of a chamfer.
- Panel mount clips from Trident
-- 1mm foam recommended for the top and rear panels
-- 3mm foam for the side panels.
- Mini12864 display housing from Trident and updated for better compatibility with the BTT version of the screen.
- Simplified Z cable chain mounts using one screw and a printed retainer.
- Updated skirt fan mounts using M3 screws and heatsets to mount the fans and fan blanks.  Inspiration for the heatset mounting method taken from Ali Express vendor.
- Revised Z gantry blocks with extra material so the printed part touches the panels before the screw heads.
- Updated suggested electronics compartment layout to match Trident.
- Electronics DIN mounting clips from Trident.
- Updated exhaust filter housing with two screws holding the filter access cover.  
- Added an exhaust filter fan grill to correct spacing for the fan mounting screws.
- Revised front idlers with tensioning screws moved to be inline with the idler pulleys.  Inspiration for this modification taken from Github issue posted by chrisingham05 (#255 ).
- Added mount for 3x5 WAGO 221 modules for inlet power wiring.
- Updated XY endstop pod compatible with both independent and PCB mounted D2F microswitches.
- Updated pulley jig for spacing assistance on all stepper pulleys and gears.
- Updated assembly manual to reflect the changes introduced by 2.4r2

### CODE REVIEW

**Review by DunarDolorgiet — APPROVED** [review]
Manual files are the correct ones for the release.
Approval does not extend to STL and CAD

**Comment by tom-miller1** [comment]
Pages 110 and 145 of the manual, you may want to add a note to wait to install the magnets until the hall effect sensor is operational. The polarity matters and it might be difficult to pry them out of their holes to reverse them if installed too early.

**Comment by T4KUUY4** [comment]
Page 220
The SSR is already using HE1 but BED_IN is still wired up

**Comment by Xeroxxx** [comment]
Page 236, 237, 239

Mentions wiring to Hotend instead of "to Toolhead" (236), "to Probe" (237) and "to Toolhead Fans" (239).

**Comment by Xeroxxx** [comment]
Page 211, 216

Attaching protective earth to frame requires sanding to remove coating with for ex. sandpaper.

Anodized aluminum is non conductive on the coating.

**Comment by garyd9** [comment]
~~Manual, page 258 (skirt fans):  There's no way M3x8's can be used to attach 60mm fans.  I suspect this page should be updated to reference M3x25's and M3 nuts to hold the fan.~~

**Comment by garyd9** [comment]
~~Change notes state "... skirt fan mounts using M3 screws and heatsets to mount the fans and fan blanks. ..."  However, the actual manual and STL files in the PR are not using heat set inserts for the skirt fan/fan blank mounts.  They are using screws (and probably nuts for the fans, but maybe screwing into plastic for the blanks.)~~

**Comment by julianschill** [comment]
> Manual, page 258 (skirt fans): There's no way M3x8's can be used to attach 60mm fans. I suspect this page should be updated to reference M3x25's and M3 nuts to hold the fan.

Check page 243. Heatset Inserts are being used.

**Comment by garyd9** [comment]
> Check page 243. Heatset Inserts are being used.

wow.  okay.  Completely missed that. Thank you.  (I never considered sticking an insert into the actual fan.)

**Comment by LordGaav** [comment]
Page 47: "Build another **Z drives**, following the same instructions." -> "Build another **Z drive**, following the same instructions." .
Page 47: "Build two more **Z drive** following the instructions that came before." -> "Build two more **Z drives** following the instructions that came before."

**Comment by shinuza** [comment]
> > Check page 243. Heatset Inserts are being used.
> 
> wow. okay. Completely missed that. Thank you. (I never considered sticking an insert into the actual fan.)

@garyd9 They are not in the fan, but in the housing 😆

**Comment by Xeroxxx** [comment]
Page 288

M5 T-Nut missing for spool holder.

**Comment by VGendlin** [comment]
Page 269 lists M3x12 SHCS for side panel clips.  I believe these should be M3x8 SHCS.  Also, page 271 lists M3x8 SHCS for rear panel clips, which should be M3x12 SHCS (or M3x10?).

**Comment by stvptrsn** [comment]
> @Xeroxxx

Please check again.  I moved all of the t-nuts to the frame assembly so people could more easily count how many are needed per extrusion in the case of needing to pre-install difficult t-nuts.  I just double checked my source file and the t-nut is there.

**Comment by stvptrsn** [comment]
> @VGendlin

The manual is correct for this.  M3x12 on the side panels to accommodate the recommendation for 3mm foam on the side panels.  The rear and top panel get 1mm foam so use M3x8.

**Comment by Xeroxxx** [comment]
> > @Xeroxxx
> 
> Please check again. I moved all of the t-nuts to the frame assembly so people could more easily count how many are needed per extrusion in the case of needing to pre-install difficult t-nuts. I just double checked my source file and the t-nut is there.

Hmm...maybe I'm wrong. I can't find it. I expected it to be like on page 284. Not a big deal :)

**Comment by wlhlm** [comment]
Awesome work on the manual. Thanks Voron Team.

Typos:
- page 81 It's -> Its
- page 201: Febuary -> February

**Review by KiloQubit — APPROVED** [review]

**Comment by VGendlin** [comment]
> The manual is correct for this. M3x12 on the side panels to accommodate the recommendation for 3mm foam on the side panels. The rear and top panel get 1mm foam so use M3x8.

M3x12 bottoms out in the rail before it is able to capture the side panel, at least on my machine.  This is with the updated 4mm clips and ~3mm thick gasket.  M3x8 is about right.  On the back, M3x8 is not long enough to thread into a t-nut, with the updated 6mm clips.  

Attaching a couple of pics.  One is with the screws as per manual.  The other is reversed (8mm in side clips, 12mm in rear).  Screw tops are flush with the top of the clips.
PXL_20220223_151308425
PXL_20220223_151241437
.

**Comment by KiloQubit** [comment]
> > The manual is correct for this. M3x12 on the side panels to accommodate the recommendation for 3mm foam on the side panels. The rear and top panel get 1mm foam so use M3x8.
> 
> M3x12 bottoms out in the rail before it is able to capture the side panel, at least on my machine. This is with the updated 4mm clips and ~3mm thick gasket. M3x8 is about right. On the back, M3x8 is not long enough to thread into a t-nut, with the updated 6mm clips.

M3x12 should be going into 6mm clips for the side panels.

M3x8 should be going into 4mm clips for the back and top panels.

**Comment by stvptrsn** [comment]
> > > @Xeroxxx
> > 
> > 
> > Please check again. I moved all of the t-nuts to the frame assembly so people could more easily count how many are needed per extrusion in the case of needing to pre-install difficult t-nuts. I just double checked my source file and the t-nut is there.
> 
> Hmm...maybe I'm wrong. I can't find it. I expected it to be like on page 284. Not a big deal :)

You didn't mention a page number before so I mistakenly thought you were referring to the CAD.

Edit: Oh wait, maybe you did mention it.  Sorry about that.

**Comment by stvptrsn** [comment]
> > The manual is correct for this. M3x12 on the side panels to accommodate the recommendation for 3mm foam on the side panels. The rear and top panel get 1mm foam so use M3x8.
> 
> M3x12 bottoms out in the rail before it is able to capture the side panel, at least on my machine. This is with the updated 4mm clips and ~3mm thick gasket. M3x8 is about right. On the back, M3x8 is not long enough to thread into a t-nut, with the updated 6mm clips.
> 
> Attaching a couple of pics. One is with the screws as per manual. The other is reversed (8mm in side clips, 12mm in rear). Screw tops are flush with the top of the clips.

Side panels = 6mm clips, 3mm foam and M3x12.
Top and Rear panels = 4mm clips, 1mm foam and M3x8.

This is the same setup transferred over from Trident.  Clip size is marked as panel thickness plus foam thickness.

**Comment by VGendlin** [comment]
> > > The manual is correct for this. M3x12 on the side panels to accommodate the recommendation for 3mm foam on the side panels. The rear and top panel get 1mm foam so use M3x8.
> > 
> > 
> > M3x12 bottoms out in the rail before it is able to capture the side panel, at least on my machine. This is with the updated 4mm clips and ~3mm thick gasket. M3x8 is about right. On the back, M3x8 is not long enough to thread into a t-nut, with the updated 6mm clips.
> > Attaching a couple of pics. One is with the screws as per manual. The other is reversed (8mm in side clips, 12mm in rear). Screw tops are flush with the top of the clips.
> 
> Side panels = 6mm clips, 3mm foam and M3x12. Top and Rear panels = 4mm clips, 1mm foam and M3x8.
> 
> This is the same setup transferred over from Trident. Clip size is marked as panel thickness plus foam thickness.

I see.  I assumed the 6mm clips go on the back as they did in the previous version.  The 4mm clips are too short for my machine (the back panel is roughly 4mm thick without tape).  Having said that, the BOM is calling for a 3mm thick back panel.  So this issue is specific to my case.  Thanks for clearing this up.

**Pull request merged**
