### PR TITLE
Creation of V2 Spider printer.cfg

### PR DESCRIPTION
**Pull request by shiftingtech**
I haven't yet fully tested this.  Should not be merged until I (or somebody) has given it a test run

### CODE REVIEW

**Comment by julianschill** [comment]
There is an extra "add" in the comment of the probe section:

If your probe is NO instead of NC, add change pin to ^PA3

**Comment by shiftingtech** [comment]
somehow I ended up with two branches of this config.  I'm going to close this P.R. only so I can create a fresh PR from the other, more up to date branch

**Comment by ELteris** [comment]
Hey I’m interested to make the voron v2 250mm can I have the stl files for the printer ?

**Comment by julianschill** [comment]
@ELteris Please do not use the issue tracker for those kind of inquiries. For questions join the Discord https://discord.com/invite/voron

Nevertheless:
You can download the STL Files here: https://github.com/VoronDesign/Voron-2/releases/tag/V2.4r1
Make sure to check out the homepage for the Bill Of Materials and Manuals: https://vorondesign.com/voron2.4
Documentation can be found here: https://docs.vorondesign.com/

Good Luck with your printer build.

**Comment by eduncan911** [comment]
New pull request is #261 that continues this work

**Pull request closed without merging**
