### PR TITLE
Updated front idlers to reduce belt wear 

### PR DESCRIPTION
**Pull request by chrisingham05**
As per the issue raised (https://github.com/VoronDesign/Voron-2/issues/255), I experienced belt wear due to tensioning screw not being centred on the bearing, creating some torque on the tensioner, causing the bearing to wear the belts. 

129440354-e07bfa2e-8b54-4c8e-9190-5d5cc9f9e6e0

### CODE REVIEW

**Comment by chrisingham05** [comment]
IdlerNew

**Comment by DanJunior78** [comment]
I am not somebody who can release your push request, but most of your STL files are not in correct orientation to print as it is. This has first to be fixed.

**Comment by CFreeman918** [comment]
Is it possible to get the STEP files for this?

**Comment by stvptrsn** [comment]
> IdlerNew

Hi Chrisingham05.  I don't know if you've seen but the next revision of V2 and Trident will be using this basic idea, just executed very slightly differently.  I'm pretty sure your issue report is where I sourced the idea so I'll be sure to credit you.

**Comment by chrisingham05** [comment]
> 
I hadn't seen that, great news, thanks!

**Comment by raymondh2** [comment]
Closing as this will be fixed with Steve's design in V2.4r2

**Pull request closed without merging**
