### PR TITLE
added a bottom panel support

### PR DESCRIPTION
**Pull request by Bleach3D**
prevents bottom acrylic sheet from bending down the edges over time

### CODE REVIEW

**Comment by stvptrsn** [comment]
Thank you, but this already exists.  The deck_support files located here: https://github.com/VoronDesign/Voron-2/tree/Voron2.4/STLs/Panel_Mounting

If I missed what you are trying to do, please clarify.

**Comment by timmit99** [comment]
My bad! Mobile misclick....

**Comment by Bleach3D** [comment]
I see. I could not find any use for that part, would not have guessed it for supporting the panel, was confused by the ziptie channel. You can close the PR if you want or add it to the user mods or so? I dont know... :D

**Comment by stvptrsn** [comment]
Thanks, if you want to share what you have done feel free to do a PR to the Voron Users repo.

**Pull request closed without merging**
