### PR TITLE
I've added files for Waveshare 5inch lcd cover

### PR DESCRIPTION
**Pull request by orkusmg**
I think enyone who is searching for solution for different screen with touch capabilities can benefit from it.

### CODE REVIEW

**Comment by orkusmg** [comment]
I have updated **Back LCD Cover** to correct file (and F360 that goes with it).

**Comment by TorinoFermic** [comment]
I don't find anything about this mod in this mods/README.md explaining about your mod.

**Comment by orkusmg** [comment]
It's my 1st pull request ever, sorry :) Description added.

**Comment by TorinoFermic** [comment]
Plus you will need leave the desc with links in forms of [name](../mods/OrkusMG/) at the root/mods/README.md then the PR is good.

**Comment by john--** [comment]
@orkusmg can you update the index at https://github.com/VoronDesign/Voron-2/blob/master/mods/README.md with info about your mod please? Thanks!

**Comment by FHeilmann** [comment]
@orkusmg hi, one thing I'd like to add is please rename your directories to something without spaces, as spaces are the bane of every linux/windows users existence when working with commandline stuff.

Did you or someone else already print this? How is the fit? Other than these minor comments the PR looks good to me, barring @john-- s comment about the README

**Comment by FHeilmann** [comment]
Filenames as well please

**Comment by orkusmg** [comment]
Filer updated, I have no clue how to change main folder name, updating main readme.md is not straight forward either for me - sorry, I don't do Linux.

Yes, this screen cover has been printed by me, also recently (color change), this fits like it shoud but it will fit only the screen I mentioned in description, plus I've used original Voron screen cover files and my mod has exactly the same mounting as the original.
IMG_20191105_231609
IMG_20191105_231639
IMG_20191105_231703

**Pull request merged**
