### PR TITLE
Update Voron2_Octopus_Config.cfg

### PR DESCRIPTION
**Pull request by jvandervyver**
Using `spi_software` means the pins for the SPI bus are being used by the mini12864 display.
Thus precluding their use by SPI driven stepper motors such as the TMC5160
If not using the PT100 sensor on the Octopus Pro, it does however require disabling the MAX31865

### CODE REVIEW

**Comment by cbc02009** [comment]
I think there might be some misunderstanding about how klipper handles SPI going on here. Klipper supports hardware SPI using each chip's SPI peripherals, but it also supports software SPI that's literally just bit-banging a gpio pin using the SPI protocol. It's true that you can't mix hardware and software spi on the same pins, but they're both still SPI and will work with all SPI peripherals that I know of.

I've successfully used software SPI with both the MAX31865 and the TMC5160s on the octopus pro.

**Comment by jvandervyver** [comment]
> I've successfully used software SPI with both the MAX31865 and the TMC5160s on the octopus pro.

Why bit-bang SPI when you can use hardware SPI?

**Comment by cbc02009** [comment]
> > I've successfully used software SPI with both the MAX31865 and the TMC5160s on the octopus pro.
> 
> Why bit-bang SPI when you can use hardware SPI?

due to the wildly different hardware implementations of SPI and differing quality of drivers from vendors combined with the fact that there aren't any real tight timing requirements or high-bandwidth usecases for klipper, software SPI has generally been more reliable.

**Comment by jvandervyver** [comment]
> due to the wildly different hardware implementations of SPI and differing quality of drivers from vendors combined with the fact that there aren't any real tight timing requirements or high-bandwidth usecases for klipper, software SPI has generally been more reliable.

If that were the case, what you describe sounds like a generic problem.  Whereas in this case the configuration is specifically for the Octopus controller which works right?

Are you are a reviewer and essentially decided already?
Although I think this is the technically superior implementation as I don't really see any relevant caveats for such a specific implementation (and in fact only drawbacks to the alternative).  But if your mind is already made up, then it is likely to save us more time not going back and forth on the review.

**Comment by cbc02009** [comment]
> Are you are a reviewer and essentially decided already?

I'm not "the reviewer", but I did write this config file. We try to decide things as a group. 

> Although I think this is the technically superior implementation as I don't really see any relevant caveats for such a specific implementation (and in fact only drawbacks to the alternative).

What drawbacks do you see with software SPI? From my point of view the drawbacks are increased latency and reduced bandwidth, but we haven't run into a situation yet where that has been an issue. I've had all 7 steppers on my v2 running software SPI plus the max31865 also running software SPI.

> But if your mind is already made up, then it is likely to save us more time not going back and forth on the review.

Up to you. Was trying to explain the reasoning. I don't like closing issues with "we don't like it we're not going to do it". 

I think we're going to continue using software SPI for the foreseeable future because it's less work for us doing troubleshooting and maintenance if all of our config files are uniform, but we're definitely open to input if there's a major improvement from making such a change.

**Comment by jvandervyver** [comment]
> I think we're going to continue using software SPI for the foreseeable future

👍

**Pull request closed without merging**
