### PR TITLE
Repair STL issues with XY Bridge and Idler Frame, side skirts were 1mm short

### PR DESCRIPTION
**Pull request by volcom8190**

### CODE REVIEW

**Comment by milesale** [comment]
Seeing a similar issue with front_rear_skirt_b.

STLs/VORON2.2/Bottom_Skirts_+_Decorative_Parts/Skirts/front_rear_skirt_b_150spec_x1_Rev2.STL
STLs/VORON2.2/Bottom_Skirts_+_Decorative_Parts/Skirts/front_rear_skirt_b_200spec_x1_Rev2.STL
STLs/VORON2.2/Bottom_Skirts_+_Decorative_Parts/Skirts/front_rear_skirt_b_250spec_x1_Rev2.stl
STLs/VORON2.2/Bottom_Skirts_+_Decorative_Parts/Skirts/front_rear_skirt_b_300spec_x1_Rev2.stl
STLs/VORON2.2/Bottom_Skirts_+_Decorative_Parts/Skirts/front_rear_skirt_b_350spec_x1_Rev2.stl

**Comment by FHeilmann** [comment]
@milesale I checked the files and they look good here. Can you confirm?

**Comment by milesale** [comment]
@FHeilmann  I should have been more clear that I was seeing the same type of corruption in those files (inverted normals / reversed facets), not that they are 1mm short.

image
`STLs/VORON2.2/Bottom_Skirts_+_Decorative_Parts/Skirts/front_rear_skirt_b_300spec_x1_Rev2.stl`

image
`STLs/VORON2.2/Bottom_Skirts_+_Decorative_Parts/Skirts/front_rear_skirt_b_250spec_x1_Rev2.stl`

**Comment by FHeilmann** [comment]
@milesale this corruption should be fixed now as well. Can you pleased check the files in this pr to confirm. I checked them with slic3r and they look fine. Just want to make sure 😊

**Comment by milesale** [comment]
@FHeilmann `front_rear_skirt_b` updated STLs look good. Thanks @volcom8190 !

**Pull request merged**
